"""empty message

Revision ID: 477851b0bdc7
Revises: 9af76a18f7d3
Create Date: 2024-09-02 14:28:55.527665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477851b0bdc7'
down_revision = '9af76a18f7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_round_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
